# Site settings
title: Kevin London's blog
email: kevinlondon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer at ChowNow.
  Master's student in Computer Science at Georgia Tech.
  This is a place for me to share thoughts on software engineering and Python.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kevinlondon.com" # the base hostname & protocol for your site
twitter_username: kevin_london
github_username:  kevinlondon
gravatar: https://s.gravatar.com/avatar/c1428d36c91a53a1e4c39fb2c7ceff15

fb_admins: https://www.facebook.com/klond
fb_appid: 788523661277156  # Kevin London's Blog

# Build settings
markdown: kramdown
locale: en_US
